apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: vlan-enp4s0-2000-test
spec:
  nodeSelector:
    kubernetes.io/hostname: quick3-1
  desiredState:
    interfaces:
    - name: enp4s0.2000
      type: vlan
      state: up
      vlan:
        base-iface: enp4s0
        id: 2000