apiVersion: v1
kind: Pod
metadata:
  name: busybox-a
  annotations:
    k8s.v1.cni.cncf.io/networks: macvlan-enp4s0-2000-test   
spec:
  containers:
  - name: nginx-container
    image: busybox:1.36
    command: ["sh", "-c", "while true; do sleep 30; done"]
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "500m"
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox-b
  annotations:
    k8s.v1.cni.cncf.io/networks: macvlan-enp4s0-2000-test   
spec:
  containers:
  - name: nginx-container
    image: busybox:1.36
    command: ["sh", "-c", "while true; do sleep 30; done"]
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "500m"